name: busco

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #arch and centos both unavailable https://github.com/actions/virtual-environments#available-environments
        python-version: [3.6, 3.9]

    steps:
    - name: initialize github actions test environment
      uses: actions/checkout@v2

    - name: setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: update the pip package manager and the setuptools and wheel libraries
      run: |
        python -m pip install -U pip setuptools wheel
        # GitHub does not always have up-to-date pip, and
        # installation from pre-built binary archives (with pip)
        # will complain if pip is out of date.
        # Up-to-date setuptools and wheel libraries
        # enable installation from source archives.

    - name: report environment variables for debugging
      run: |
        printf '%s\n' \
          "Workflow ${GITHUB_WORKFLOW}" \
          "Action Number ${GITHUB_ACTION}" \
          "Run ID ${GITHUB_RUN_ID}" \
          "Run Number ${GITHUB_RUN_NUMBER}" \
          "Workspace ${GITHUB_WORKSPACE}"

    - name: report python version
      run: |
        python -c 'import sys; print(sys.version)'

    - name: setup workspace
      run: |
        mkdir -v "${GITHUB_WORKSPACE}/Downloads"

    - name: install busco with conda
      run: |
        conda create -n my_env -c conda-forge -c bioconda busco=4.1.4 -y

    - name: test busco
      run: |
        source "${CONDA}/bin/activate" my_env
        echo 'debug step 1'
        tree $(dirname $(dirname $(which run_busco)))
        echo 'debug step 2'
        tree $(dirname $(dirname $(which busco)))
        busco -h
        busco --help
        busco -v
        busco --version
        mkdir Downloads/gitlab_src_busco
        wget -O Downloads/gitlab_src_busco/busco-4.1.4.tar.gz \
         https://gitlab.com/ezlab/busco/-/archive/4.1.4/busco-4.1.4.tar.gz
        tar zxvf Downloads/gitlab_src_busco/busco-4.1.4.tar.gz \
         --directory Downloads/gitlab_src_busco --strip-components=1
        busco -i Downloads/gitlab_src_busco/test_data/bacteria/genome.fna \
         -m geno -f --out outdir
        tree outdir
        diff outdir/output.log \
         Downloads/gitlab_src_busco/test_data/bacteria/expected_log.txt
        # https://gitlab.com/ezlab/busco/-/blob/b40b3ba2d3c5b4793bc9d42416d9a3aebccb6752/test_data/bacteria/expected_log.txt
        #  recommends comparing logfile but tough due to paths and timestamps
        grep $'\t|C:' outdir/output.log
        echo "diff comparison returned: $?"
